export const COLLEGE_INFO = {
  name: 'RAJIV GANDHI COLLEGE OF ENGINEERING & TECHNOLOGY',
  portalTitle: 'Admission Portal',
  systemName: 'Academic ERP System',
  version: 'Version 2.x',
  tagline: '(Approved by AICTE & Affiliated to Pondicherry University)',
};

export const DISTRICTS = [
  'Puducherry',
  'Karaikal',
  'Mahe',
  'Yanam',
  'Chennai',
  'Coimbatore',
  'Cuddalore',
  'Kanchipuram',
  'Madurai',
  'Salem',
  'Tiruchirappalli',
  'Vellore',
  'Villupuram',
  'Other District',
];

export const DEPARTMENTS_BY_PROGRAM: Record<string, string[]> = {
  'First Year B.Tech': [
    'Computer Science & Engineering (CSE)',
    'Electronics & Communication Engineering (ECE)',
    'Electrical & Electronics Engineering (EEE)',
    'Mechanical Engineering (MECH)',
    'Civil Engineering (CIVIL)',
    'Artificial Intelligence and Machine Learning (AI&ML)',
    'Artificial Intelligence and Data Science (AI&DS)',
    'Information Technology (IT)',
    'Biomedical Engineering (BME)',
  ],
  'Second Year B.Tech (Lateral Entry)': [
    'Computer Science & Engineering (CSE)',
    'Electronics & Communication Engineering (ECE)',
    'Electrical & Electronics Engineering (EEE)',
    'Mechanical Engineering (MECH)',
    'Civil Engineering (CIVIL)',
    'Artificial Intelligence and Machine Learning (AI&ML)',
    'Artificial Intelligence and Data Science (AI&DS)',
    'Information Technology (IT)',
    'Biomedical Engineering (BME)',
  ],
  PG: [
    'MTech CSE',
    'M.Tech Wireless Communication',
    'Master of Business Administration',
    'MCA',
  ],
};

export interface BusStopDetails {
  stopName: string;
  fee: number;
}

export const BUS_ROUTES_WITH_STOPS: Record<string, BusStopDetails[]> = {
  'Kalapet': [
    { stopName: 'Koonimedu', fee: 26000 },
    { stopName: 'Ranganathapuram', fee: 26000 },
    { stopName: 'Manjakuppam', fee: 26000 },
    { stopName: 'Kilputhupattu', fee: 26000 },
    { stopName: 'Kanagachettikulam Arch', fee: 26000 },
    { stopName: 'University', fee: 26000 },
    { stopName: 'PEC', fee: 26000 },
    { stopName: 'Auroville', fee: 25000 },
    { stopName: 'Kottakuppam', fee: 25000 },
    { stopName: 'Ezhai Mariamman Koil', fee: 25000 },
    { stopName: 'Hotel Lotus', fee: 25000 },
    { stopName: 'S.S. Thirumana Nilayam', fee: 25000 },
    { stopName: 'Central Bank', fee: 25000 },
    { stopName: 'G.H', fee: 25000 },
    { stopName: 'Old Law College', fee: 25000 },
    { stopName: 'Water Tank', fee: 24000 },
    { stopName: 'Railway Station', fee: 24000 },
    { stopName: 'Old Bus Stand', fee: 24000 },
    { stopName: 'New Bus Stand', fee: 24000 },
    { stopName: 'Madhava Hospital', fee: 24000 },
    { stopName: 'Cement Road', fee: 23000 },
    { stopName: 'Murugan Koil', fee: 23000 },
    { stopName: 'Petrol Bunk', fee: 23000 },
    { stopName: 'Marapalam', fee: 23000 },
    { stopName: 'RGCET', fee: 0 },
  ],
  'Neyveli': [
    { stopName: 'Neyveli Township / Sevvai Sandhai', fee: 28000 },
    { stopName: 'Indra Nagar / Arch Gate', fee: 28000 },
    { stopName: 'Kadampuliyur', fee: 27000 },
    { stopName: 'Panruti', fee: 25000 },
    { stopName: 'Link Road', fee: 25000 },
    { stopName: 'Pakkiripalayam', fee: 25000 },
    { stopName: 'Andikuppam', fee: 25000 },
    { stopName: 'Pattampakkam', fee: 25000 },
    { stopName: 'Vazhapattu', fee: 24000 },
    { stopName: 'Nellikuppam', fee: 24000 },
    { stopName: 'Nathapattu', fee: 24000 },
    { stopName: 'Karupu Gate', fee: 24000 },
    { stopName: 'Vella Gate', fee: 24000 },
    { stopName: 'Kondur', fee: 24000 },
    { stopName: 'Savadi', fee: 22000 },
    { stopName: 'Employement Office', fee: 21000 },
    { stopName: 'Railway Gate', fee: 21000 },
    { stopName: 'Kambianpettai', fee: 21000 },
    { stopName: 'Register Office', fee: 21000 },
    { stopName: 'Vandipalayam Bypass', fee: 21000 },
    { stopName: 'Kamalam Theatre', fee: 21000 },
    { stopName: 'Semmandalam', fee: 21000 },
    { stopName: 'RGCET', fee: 0 },
  ],
  'Chidambaram': [
    { stopName: 'Vallampadugai', fee: 28000 },
    { stopName: 'Therkuvani Street (Police Line)', fee: 27000 },
    { stopName: 'Chidambaram Pacchaiappan School', fee: 27000 },
    { stopName: 'Noothanam Shopping Mall', fee: 27000 },
    { stopName: 'CRC Bus Shed', fee: 27000 },
    { stopName: 'Telephone Exchange', fee: 27000 },
    { stopName: 'T. Paalayam Junction (B. Muthlur)', fee: 26000 },
    { stopName: 'B. Muthlur MGR Statue', fee: 26000 },
    { stopName: 'Kothattai', fee: 25000 },
    { stopName: 'Pudhuchathiram', fee: 25000 },
    { stopName: 'Periyapattu', fee: 25000 },
    { stopName: 'Alappakkam Railway Gate', fee: 24000 },
    { stopName: 'SIPCOT (Cuddalore)', fee: 23000 },
    { stopName: 'Housing Board', fee: 23000 },
    { stopName: 'Suthukulam', fee: 23000 },
    { stopName: 'Cuddalore OT Railway Station', fee: 23000 },
    { stopName: 'Cuddalore OT Police Station', fee: 23000 },
    { stopName: 'Saalakarai', fee: 23000 },
    { stopName: 'Cuddalore Seemati', fee: 21000 },
    { stopName: 'New Cinema', fee: 21000 },
    { stopName: 'Cuddalore Post Office', fee: 21000 },
    { stopName: 'Kirshnasamy School', fee: 21000 },
    { stopName: 'Aalpettai Checkpost', fee: 19000 },
    { stopName: 'Periyakanganankuppam', fee: 19000 },
    { stopName: 'RGCET', fee: 0 },
  ],
  'JIPMER': [
    { stopName: 'Thattanchavady Bus Stop', fee: 25000 },
    { stopName: 'V.V.P Nagar Stop', fee: 25000 },
    { stopName: 'JIPMER', fee: 25000 },
    { stopName: 'Police Complex', fee: 25000 },
    { stopName: 'Mettupalayam', fee: 25000 },
    { stopName: 'Ramanapuram', fee: 25000 },
    { stopName: 'Shanmugapuram', fee: 25000 },
    { stopName: 'Indra Gandhi Arts College', fee: 25000 },
    { stopName: 'Gandhi Nagar', fee: 25000 },
    { stopName: 'Kasthuri Bai Nagar', fee: 25000 },
    { stopName: 'Muruga Theatre', fee: 25000 },
    { stopName: 'Saradhambal Koil', fee: 24000 },
    { stopName: 'Indra Gandhi Signal', fee: 24000 },
    { stopName: 'RTO', fee: 23000 },
    { stopName: 'Marapalam', fee: 23000 },
    { stopName: 'Nainarmandapam', fee: 23000 },
    { stopName: 'Murungapakkam', fee: 23000 },
    { stopName: 'Ariyankuppam', fee: 21000 },
    { stopName: 'RGCET', fee: 0 },
  ],
  'Villianur': [
    { stopName: 'Indira Gandhi Statue', fee: 25000 },
    { stopName: 'Ellaipillaichavady', fee: 25000 },
    { stopName: 'Hotel Nalas', fee: 25000 },
    { stopName: 'Ajees Nagar', fee: 25000 },
    { stopName: 'Kaveri Nagar', fee: 25000 },
    { stopName: 'Kamban Nagar', fee: 25000 },
    { stopName: 'Jaya Nagar', fee: 25000 },
    { stopName: 'Salai Street', fee: 25000 },
    { stopName: 'Moolakulam', fee: 25000 },
    { stopName: 'Villianur', fee: 25000 },
    { stopName: 'Kottaimedu', fee: 23000 },
    { stopName: 'Achariyapuram', fee: 23000 },
    { stopName: 'Uruvaiyar', fee: 23000 },
    { stopName: 'Korkadu', fee: 23000 },
    { stopName: 'Karikkalampakkam', fee: 23000 },
    { stopName: 'Abishekapakkam', fee: 23000 },
    { stopName: 'Thavalakuppam', fee: 22000 },
    { stopName: 'RGCET', fee: 15000 },
  ],
  'Lawspet': [
    { stopName: 'Sivaji Statue', fee: 25000 },
    { stopName: 'Karuvadikuppam', fee: 25000 },
    { stopName: 'Vinayagar Koil', fee: 25000 },
    { stopName: 'Sellaperumal Pet', fee: 25000 },
    { stopName: 'Iyanar Koil', fee: 25000 },
    { stopName: 'Uzhavar Sandhai', fee: 25000 },
    { stopName: 'JTS School', fee: 25000 },
    { stopName: 'Navalar School', fee: 25000 },
    { stopName: 'Vanavil', fee: 25000 },
    { stopName: 'Kurinji Nagar', fee: 25000 },
    { stopName: 'Sellaperumal Vinayager Koil', fee: 25000 },
    { stopName: 'Latha Steel', fee: 25000 },
    { stopName: 'Rajiv Gandhi Statue', fee: 25000 },
    { stopName: 'Saram', fee: 25000 },
    { stopName: 'Balaji Theatre', fee: 25000 },
    { stopName: 'Raja Theatre', fee: 25000 },
    { stopName: 'Ram International', fee: 25000 },
    { stopName: 'Anthoniar Koil', fee: 24000 },
    { stopName: 'AFT Mill', fee: 24000 },
    { stopName: 'Mudaliyarpet', fee: 24000 },
    { stopName: 'RGCET', fee: 0 },
  ],
};

export const HOSTEL_FEE_PER_YEAR = 72000;

export const STANDARD_CERTIFICATES = [
  'Provisional Allotment Order',
  'Special Category Certificate',
  'Provisional Certificate',
  'Undertaking Form',
  'Mark Sheet',
  'Degree Certificate',
  'Residence Certificate',
  'Transfer Certificate',
  'Proof of Age',
  'Community Certificate',
  'Conduct Certificate',
  'Aadhaar Card',
];

export const ARCHIVE_REASONS = [
  'Transfer Certificate (TC)',
  'Admission Cancelled',
  'Duplicate Admission',
  'Course Discontinued',
  'Student Request',
  'Management Decision',
  'Other',
];
